name: "Free Disk Space (Ubuntu)"
description: "A configurable GitHub Action to free up disk space on an Ubuntu GitHub Actions runner."

# See: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#branding
branding:
  icon: "trash-2"
  color: "green"

inputs:
  android:
    description: "Remove Android runtime"
    required: false
    default: "true"
  az:
    description: "Remove Azure CLI"
    required: false
    default: "true"
  aws-cli:
    description: "Remove AWS CLI"
    required: false
    default: "true"
  browsers:
    description: "Remove Browsers (Chrome, Chromium, Edge and Firefox)"
    required: false
    default: "true"
  gcc:
    description: "Remove GCC"
    required: false
    default: "true"
  google-cloud-sdk:
    description: "Remove Google Cloud SDK"
    required: false
    default: "true"
  docker-images:
    description: "Remove Docker images"
    required: false
    default: "true"
  dotnet:
    description: "Remove .NET runtime"
    required: false
    default: "true"
  jvm:
    description: "Remove JVM runtime"
    required: false
    default: "true"
  julia:
    description: "Remove Julia runtime"
    required: false
    default: "true"
  haskell:
    description: "Remove Haskell runtime"
    required: false
    default: "true"
  heroku:
    description: "Remove Heroku"
    required: false
    default: "true"
  llvm:
    description: "Remove LLVM"
    required: false
    default: "true"
  mono:
    description: "Remove Mono runtime"
    required: false
    default: "true"
  mysql:
    description: "Remove MySQL"
    required: false
    default: "true"
  node:
    description: "Remove Node runtime"
    required: false
    default: "true"
  python:
    description: "Remove Python runtime"
    required: false
    default: "true"
  postgresql:
    description: "Remove PostgreSQL"
    required: false
    default: "true"
  powershell:
    description: "Remove Powershell runtime"
    required: false
    default: "true"
  ruby:
    description: "Remove Ruby runtime"
    required: false
    default: "true"
  rust:
    description: "Remove Rust runtime"
    required: false
    default: "true"
  snap:
    description: "Remove Snap"
    required: false
    default: "true"
  swift:
    description: "Remove Swift runtime"
    required: false
    default: "true"
  # option inspired by:
  # https://github.com/actions/virtual-environments/issues/2875#issuecomment-1163392159
  tool-cache:
    description: "Remove image tool cache"
    required: false
    default: "true"

  # Disabled by default options
  usrmisc:
    description: "Remove /usr/{,local}/share/{man,doc,icons}"
    required: false
    default: "false"
  usrlocal:
    description: "Remove /usr/local"
    required: false
    default: "false"
  opt:
    description: "Remove /opt"
    required: false
    default: "false"
  varcache:
    description: "Remove /var/cache"
    required: false
    default: "false"
  swap-storage:
    description: "Remove swap storage"
    required: false
    default: "false"
  debug:
    description: "Debug options, do not enable unless for testing purposes"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        REMOVE_ANDROID: ${{ inputs.android }}
        REMOVE_AZ: ${{ inputs.az }}
        REMOVE_AWS_CLI: ${{ inputs.aws_cli }}
        REMOVE_BROWSERS: ${{ inputs.browsers }}
        REMOVE_GCC: ${{ inputs.gcc }}
        REMOVE_GOOGLE_CLOUD_SDK: ${{ inputs.google-cloud-sdk }}
        REMOVE_DOCKER_IMAGES: ${{ inputs.docker-images }}
        REMOVE_DOTNET: ${{ inputs.dotnet }}
        REMOVE_JVM: ${{ inputs.jvm }}
        REMOVE_JULIA: ${{ inputs.julia }}
        REMOVE_HASKELL: ${{ inputs.haskell }}
        REMOVE_HEROKU: ${{ inputs.heroku }}
        REMOVE_LLVM: ${{ inputs.llvm }}
        REMOVE_MONO: ${{ inputs.mono }}
        REMOVE_MYSQL: ${{ inputs.mysql }}
        REMOVE_NODE: ${{ inputs.node }}
        REMOVE_PYTHON: ${{ inputs.python }}
        REMOVE_POSTGRESQL: ${{ inputs.postgresql }}
        REMOVE_POWERSHELL: ${{ inputs.powershell }}
        REMOVE_RUBY: ${{ inputs.ruby }}
        REMOVE_RUST: ${{ inputs.rust }}
        REMOVE_SNAP: ${{ inputs.snap }}
        REMOVE_SWIFT: ${{ inputs.swift }}
        REMOVE_TOOL_CACHE: ${{ inputs.tool-cache }}
        REMOVE_USRMISC: ${{ inputs.usrmisc }}
        REMOVE_USRLOCAL: ${{ inputs.usrlocal }}
        REMOVE_OPT: ${{ inputs.opt }}
        REMOVE_VARCACHE: ${{ inputs.varcache }}
        REMOVE_SWAP_STORAGE: ${{ inputs.swap-storage }}
        DEBUG: ${{ inputs.DEBUG }}
      run: ${{ github.action_path }}/script.sh
